### ISSUE TITLE
About the background label setting 

### ISSUE THREAD

**Issue by typ1012** [happy-lifi/BCNet#2]
The label of the background score is generated using temporal Intersection-over-Anchor in the paper, while the maximum iou is used in the code.  Why?

**Comment by happy-lifi** [comment]
Hi,
Thank you for your interest in our work and for pointing this out. We have fixed this bug(https://github.com/happy-lifi/BCNet/blob/2e3b754798c60966c6f488e4ec6d7965024959ab/lib/dataset/dataset_thu_abi.py#L176). The fixed code can achieve our provided model performance. If you have other problems, Let me know. Thanks.
